######################################################################
#
# File name : ddg_simulate.do
# Created on: Thu Dec 03 18:06:26 +0100 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib ddg_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ddg_wave.do}

view wave
view structure
view signals

do {ddg.udo}

run 1000ns
