######################################################################
#
# File name : ddg_compile.do
# Created on: Thu Dec 03 18:06:21 +0100 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vlib questa_lib/work
C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../../hdl/cont_sap.vhd" \
"../../../../../hdl/ddg.vhd" \


quit -force

