######################################################################
#
# File name : ddg_wave.do
# Created on: Thu Dec 03 18:06:26 +0100 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
