######################################################################
#
# File name : ddg_elaborate.do
# Created on: Thu Dec 03 18:06:24 +0100 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vopt -64 +acc=npr -L xil_defaultlib -L secureip -work xil_defaultlib xil_defaultlib.ddg -o ddg_opt

quit -force
