######################################################################
#
# File name : TC_statemachine_tb.udo
# Created on: Fri Jan 22 09:51:08 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
