######################################################################
#
# File name : TC_statemachine_tb_simulate.do
# Created on: Wed Mar 03 16:12:56 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib TC_statemachine_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {TC_statemachine_tb_wave.do}

view wave
view structure
view signals

do {TC_statemachine_tb.udo}

run 10000ns
