######################################################################
#
# File name : TC_statemachine_tb_elaborate.do
# Created on: Wed Mar 03 16:12:54 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vopt -64 +acc=npr -L fifo_generator_v13_2_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.TC_statemachine_tb xil_defaultlib.glbl -o TC_statemachine_tb_opt

quit -force
